CREATE DATABASE mon;

GRANT ALL PRIVILEGES ON mon.* TO mon@'localhost' IDENTIFIED BY 'mon';

FLUSH PRIVILEGES ;

USE mon;


CREATE TABLE MON_LIST (
   ID	    CHAR(5) NOT NULL,
   NAME     VARCHAR(30) NOT NULL,
   STATE       CHAR(10) NOT NULL DEFAULT 'green',
   MIC        CHAR(100) NULL,
   EXPLANATION  VARCHAR(30) NOT NULL,
   DEPART       VARCHAR(30) NOT NULL,
   REGNAME     VARCHAR(30) NOT NULL
   PRIMARY KEY (ID)
);



CREATE TABLE MON_DETAIL (
   ID	    CHAR(5) NOT NULL,
   NAME     VARCHAR(30) NOT NULL,
   REG_DT       DATETIME,
   MIC        CHAR(100) NULL,
   STATE       CHAR(10) NOT NULL DEFAULT 'green',
   DESCR  VARCHAR(30) NOT NULL,
   EXPLANATION  VARCHAR(30) NOT NULL,
   DEPART       VARCHAR(30) NOT NULL,
   REGNAME     VARCHAR(30) NOT NULL
   PRIMARY KEY (ID)
);


INSERT INTO MON_LIST (ID, NAME, STATE, MIC, EXPLANATION, DEPART , REGNAME ) VALUES('I_24','현물매매','green','담당자','INFRA 설명','infra','쿠키갑세팅');
INSERT INTO MON_DETAIL (ID, NAME, STATE, MIC, STATE, DESCR, EXPLANATION, DEPART , REGNAME ) VALUES('I_24','현물매매','green','테스트','INFRA 설명','infra','쿠키갑세팅');


COMMIT;
